import { Ubuntu } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const ubuntu = Ubuntu({
  subsets: ["latin"],  
  weight: ["400", "700"], 
});

export const metadata = {
  title: "MovieLog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        <Layout>
        {children}
        </Layout>
      </body>
    </html>
  );
}
