import { Ubuntu } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import { ThemeProvider } from "@/context/ThemeContext"; 
import { AuthProvider } from '@/context/AuthContext';
import BackgroundImage from "@/components/BackgroundImage";
import Navbar from "@/components/Navbar";

const ubuntu = Ubuntu({
  subsets: ["latin"],  
  weight: ["400", "700"], 
});

export const metadata = {
  title: "MovieLog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
      <AuthProvider>
      <ThemeProvider>
        <Navbar/>
        <Layout>
          <BackgroundImage/>
            {children}
        </Layout>
      </ThemeProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
